name: Docker CI/CD

on: [push]

env:
  IMAGE: docker.pkg.github.com/rose-cream-pass-ta/backend/rose-cream-pass-ta

jobs:
  build-and-push:
    name: Build image and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Log in to Repositry
        run: docker login docker.pkg.github.com --username ${{ secrets.GITHUB_USER }} --password ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: docker build -t $IMAGE .
      - name: Push
        run: docker push $IMAGE
      - uses: citizen-of-planet-earth/cf-cli-action@master
        with:
          cf_api: ${{ secrets.CF_ENDPOINT }}
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          command: push rose-cream-pasta --docker-image $IMAGE --docker-username ${{ secrets.GITHUB_USER }}
          cf_docker_password: ${{ secrets.GITHUB_TOKEN }}
