name: Docker CI/CD

on: [push]

env:
  IMAGE: docker.pkg.github.com/rose-cream-pass-ta/backend/rose-cream-pass-ta

jobs:
  build-and-push:
    name: Build image and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Log in to Repositry
        run: docker login docker.pkg.github.com --username ${{ secrets.GITHUB_USER }} --password ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: docker build -t $IMAGE .
      - name: Push
        run: docker push $IMAGE
      - name: Log in to CF
        run: cf login --skip-ssl-validation -a ${{ secrets.CF_ENDPOINT }} -u ${{ secrets.CF_USERNAME }} -p ${{ secrets.CF_PASSWORD }}
      - name: Deploy
        run: cf push rose-cream-pasta --docker-image $IMAGE --docker-username ${{ secrets.GITHUB_USER }}
        env:
          CF_DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
